version: '3.9'

services:
  postgres:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_DB: "big_data_snowflake"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "DogeCoin"
    ports:
      - "30000:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "30001:8123"
      - "30002:9000"
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_logs:/var/log/clickhouse-server

  spark:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "30003:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - postgres
      - clickhouse
